name = "Minecraft Industiral Complex"
author = "benmac"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a2f288b64d6498b16c281c69bd16caa45169f8f00bd89730b89694e68a358ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
