name = "Minecraft Industiral Complex"
author = "benmac"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c20f860ac1f7701758c21939ecc1b3d29eadfedbeb93e7cef3f90c346356b481"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
