name = "Minecraft Industiral Complex"
author = "benmac"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b91d804a2d40b160390d8b684eb58c26656d3cf05b86ecfaa7394d015c2cc1f6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
