ServerEvents.recipes(e => {
  const removeItems = [
    "flintnpowder:steel_ingot",
    "flintnpowder:steel_nugget",
    "flintnpowder:single_action_revolver",
    "flintnpowder:trapdoor_rifle",
    "flintnpowder:break_action_coachgun",
    "flintnpowder:oil_flask",
    "flintnpowder:shotgun",
    "flintnpowder:bolt_action_rifle",
    "flintnpowder:bayinet_bolt_action_rifle",
    "flintnpowder:blowback_handback",
    "flintnpowder:open_bolt_smg",
    "flintnpowder:closed_bolt_mag_rifle",
    "flintnpowder:gas_operated_shotgun",
    "flintnpowder:handgun_mag",
    "flintnpowder:empty_handgun",
    "flintnpowder:rifle_mag",
    "flintnpowder:empty_rifle_mag",
    "flintnpowder:shotgun_magazine",
    "flintnpowder:empty_shotgun_magazine",
    "flintnpowder:greek_fire_buckshot",
    "flintnpowder:greek_fire_charge",
    "flintnpowder:flaming_buckshot",
    "flintnpowder:steel_barrel",
    "flintnpowder:steel_heavy_barrel",
    "flintnpowder:cast_iron_barrel",
    "flintnpowder:cast_iron_heavy_barrel",
    "flintnpowder:blazing_brass_barrel",
    "flintnpowder:blazing_brass_heavy_barrel",
    "flintnpowder:gun_metal_heavy_barrel",
    "flintnpowder:gun_metal_barrel",
    "flintnpowder:cast_iron_bore_drill",
    "flintnpowder:diamond_bore_drill",
    "flintnpowder:netherite_bore_drill",
    "flintnpowder:blazing_powder",
    "flintnpowder:blazing_brass",
    "flintnpowder:blazing_brass_block",
    "flintnpowder:flintlock_mechanism",
    "flintnpowder:big_game",
    "flintnpowder:bruttbuss",
    "flintnpowder:rifle_craft",
    "flintnpowder:gunmetal_alloy",
    "flintnpowder:palladium_green",
    "flintnpowder:masterful_repair_kit",
    "flintnpowder:gunmetal_ingot",
    "flintnpowder:gunmetal_block",
    "flintnpowder:cast_iron_block",
    "flintnpowder:cast_iron_ingot",
    "flintnpowder:cast_iron_nugget",
    "flintnpowder:steel_block",
    "flintnpowder:cast_iron_alloy",
    "flintnpowder:blazing_brass_alloy",
    "flintnpowder:blaze_lock_mechanism",
    "flintnpowder:blowback_handgun",
    "flintnpowder:empty_handgun_mag",
    "flintnpowder:bayonet_bolt_action_rifle",
  ];
  removeItems.forEach(id => e.remove({ output: id }));
  e.shaped('flintnpowder:flintlock_mechanism', [
    'PS ',
    ' PF',
    ' TP'
  ], {
      P: 'alloyed:steel_sheet',
      S: 'vintage:small_steel_spring',
      F: 'minecraft:flint',
      T: 'minecraft:tripwire_hook'
    });
});
